apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-notification-service
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.notificationService.service.type }}
  ports:
    - port: {{ .Values.notificationService.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "todo-chatbot.selectorLabels" . | nindent 4 }}
    app: notification-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-notification-service-dapr
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3500
      protocol: TCP
      name: http
  selector:
    {{- include "todo-chatbot.selectorLabels" . | nindent 4 }}
    app: notification-service