apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-websocket-service
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.websocketService.service.type }}
  ports:
    - port: {{ .Values.websocketService.service.port }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    {{- include "todo-chatbot.selectorLabels" . | nindent 4 }}
    app: websocket-service
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-websocket-service-dapr
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3500
      protocol: TCP
      name: http
  selector:
    {{- include "todo-chatbot.selectorLabels" . | nindent 4 }}
    app: websocket-service